/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.MaskFormatter;
import javax.swing.text.TableView;

import br.qg.loja.integracao.DAOFactory;
import br.qg.loja.modelo.Obreiro;
import visao.IOManagement.jtable.JTableFormatter;
import visao.IOManagement.jtable.ZebraRenderer;

/**
 *
 * @author RafaelQG
 */
public class JPanelRelatorioBasico extends javax.swing.JPanel {


    /**
     * Creates new form JPanelRelatorio
     */
    public JPanelRelatorioBasico() {
        initComponents();
        cargaInicial();
        this.jTableRelatorio.setRowHeight(21);
        this.jTableRelatorio.setAutoCreateRowSorter(true);
    }

    
    private void cargaInicial() {
        limpaTabela();
        ArrayList<Obreiro> lista = DAOFactory.getDAOObreiro().buscaObreiros();
        for (Obreiro obj : lista) {
            insereObreiroTabela(obj);
        }
        if (lista.isEmpty()) {
            this.jLabelSearchResult.setText(JTableFormatter.NO_RESULT_FOUND_LABEL);
        } else {
            this.jLabelSearchResult.setText("Foram encontrados " + lista.size() + " registros");
        }
        this.jTableRelatorio.setDefaultRenderer(Object.class, new ZebraRenderer());//set zebra rows
       
    }

    private void limpaTabela() {
        DefaultTableModel model = (DefaultTableModel) this.jTableRelatorio.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    private void insereObreiroTabela(Obreiro obj) {
        DefaultTableModel model = (DefaultTableModel) this.jTableRelatorio.getModel();
        Vector data = new Vector();
        data.add(obj.getIme());
        data.add(obj.getNome());
        data.add(obj.getRg());
        data.add(obj.getCpf());
        data.add(obj.getEmail());
        model.addRow(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jTextFieldFiltro = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelSearchResult = new javax.swing.JLabel();

        jTableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IME", "Nome do obreiro", "RG", "CPF", "e-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRelatorio.getTableHeader().setReorderingAllowed(false);
        jTableRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableRelatorioMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRelatorio);

        jLabelBusca.setText("Nome ou IME do obreiro:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelSearchResult.setText("Resultado da busca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelSearchResult)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabelBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSearchResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filtro = this.jTextFieldFiltro.getText();
        limpaTabela();
        ArrayList<Obreiro> lista = DAOFactory.getDAOObreiro().buscaObreiroBasico(filtro);
        if (lista.isEmpty()) {
            this.jLabelSearchResult.setText(JTableFormatter.NO_RESULT_FOUND_LABEL);
        } else {
            this.jLabelSearchResult.setText("Foram encontrados " + lista.size() + " registros");
        }
        for (Obreiro obj : lista) {
            insereObreiroTabela(obj);
        }
        this.jTableRelatorio.setDefaultRenderer(Object.class, new ZebraRenderer());//set zebra rows
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargaInicial();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableRelatorioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRelatorioMouseReleased
        int row = this.jTableRelatorio.getSelectedRow();
        int ime = Integer.valueOf(String.valueOf(this.jTableRelatorio.getValueAt(row, 0)));
        if (this.getCursor().getType()!= Cursor.WAIT_CURSOR){ // avoid more than one click while processing
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            try {
                JFramePrincipal.showForm(ime);
            } finally {
                this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        }
    }//GEN-LAST:event_jTableRelatorioMouseReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelBusca;
    private javax.swing.JLabel jLabelSearchResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRelatorio;
    private javax.swing.JTextField jTextFieldFiltro;
    // End of variables declaration//GEN-END:variables
}
